# Generated by Django 5.2.1 on 2025-06-05 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partidos', '0004_campanas_partidos_planesgobierno_comentarios_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campanas',
            name='partido',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='partidos.partidos'),
            preserve_default=False,
        ),
    ]
