# Generated by Django 5.2.1 on 2025-06-12 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partidos', '0005_campanas_partido'),
    ]

    operations = [
        migrations.AddField(
            model_name='postulantes',
            name='biografia',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='postulantes',
            name='imagen',
            field=models.ImageField(blank=True, upload_to='postulantes/'),
        ),
        migrations.AddField(
            model_name='postulantes',
            name='propuestas',
            field=models.TextField(blank=True),
        ),
    ]
