# Generated by Django 5.2.1 on 2025-06-13 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partidos', '0006_postulantes_biografia_postulantes_imagen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postulantes',
            name='imagen',
            field=models.URLField(blank=True),
        ),
    ]
