# Generated by Django 5.2.1 on 2025-06-13 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partidos', '0007_alter_postulantes_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='postulantes',
            name='criticas',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='postulantes',
            name='historia',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='postulantes',
            name='logros',
            field=models.TextField(blank=True),
        ),
    ]
