# Generated by Django 5.2.1 on 2025-06-18 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partidos', '0008_postulantes_criticas_postulantes_historia_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Presidente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('img', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='SeccionPresidente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('presidente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secciones', to='partidos.presidente')),
            ],
        ),
        migrations.CreateModel(
            name='ContenidoSeccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('seccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contenido', to='partidos.seccionpresidente')),
            ],
        ),
    ]
