# Generated by Django 5.2.1 on 2025-06-18 21:16

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partidos', '0009_presidente_seccionpresidente_contenidoseccion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seccionpresidente',
            name='presidente',
        ),
        migrations.AddField(
            model_name='presidente',
            name='bibliografia',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='presidente',
            name='criticas',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='presidente',
            name='despues_de_la_presidencia',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='presidente',
            name='logros',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='presidente',
            name='que_hizo_en_su_partido',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='presidente',
            name='img',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
        migrations.DeleteModel(
            name='ContenidoSeccion',
        ),
        migrations.DeleteModel(
            name='SeccionPresidente',
        ),
    ]
