# Generated by Django 5.2.1 on 2025-06-19 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partidos', '0010_remove_seccionpresidente_presidente_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presidente',
            name='img',
        ),
        migrations.AddField(
            model_name='presidente',
            name='iimg',
            field=models.URLField(blank=True),
        ),
    ]
