# Generated by Django 5.2.1 on 2025-06-19 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partidos', '0011_remove_presidente_img_presidente_iimg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presidente',
            name='iimg',
        ),
        migrations.AddField(
            model_name='presidente',
            name='img',
            field=models.URLField(blank=True),
        ),
    ]
